on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: environment variable declaration
        env:
         APP_NAME: CI_PLAYGROUND
         BRANCH_NAME: DEVELOPMENT
        run: |
          echo "My application name is -> $APP_NAME"
          echo "My branch name -> $BRANCH_NAME"
      - name: check out version v3 for configuration
        uses: actions/checkout@v3
      - name: Setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: cache maven dependency
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: run maven compile
        run: mvn clean build






