on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check what is installed
        run: |
          echo "Java version:"
          java -version
          echo "maven version:"
          mvn -version
          echo "Docker version:"
          docker --version
          echo "Node version:"
          node --version



